defaults:
  - config_schema
  - _self_

data:
  train_dir: data/train
  val_dir: data/val
  train_archive: data/train.tar.gz
  val_archive: data/val.tar.gz
  dvc_remote: s3_remote
  force_extract: false
  num_workers: 1
  batch_size: 128

model:
  model_name: efficientnet_b0
  num_classes: 2
  pretrained: true
  output_path: artifacts/efficientnet_b0.pth

logger:
  experiment_name: cats_vs_bread_experiment
  tracking_uri: "http://127.0.0.1:8080"

train:
  max_epochs: 3
  learning_rate: 0.0001

git_commit_id: ${git_commit_id:}
